apiVersion: v1
kind: Service
metadata:
  name: {{ include "xjltest.fullname" . }}
  labels:
    {{- include "xjltest.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: main-port
      port: 8080
      protocol: TCP
      targetPort: main-port
    - name: manage-port
      port: 8081
      protocol: TCP
      targetPort: manage-port
  selector:
    {{- include "xjltest.selectorLabels" . | nindent 4 }}
#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ include "xjltest.fullname" . }}
#  labels:
#    {{- include "xjltest.labels" . | nindent 4 }}
#spec:
#  type: ClusterIP
#  ports:
#    - name: main-port
#      port: 8080
#      protocol: TCP
#      targetPort: main-port
#    - name: manage-port
#      port: 8081
#      protocol: TCP
#      targetPort: manage-port
#  selector:
#    {{- include "xjltest.selectorLabels" . | nindent 4 }}
