name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
            java-version: '21'  # 使用JDK 21
            distribution: 'adopt'  # 设置分发版本

      - name: Build with Gradle
        run: |
          ./gradlew build
          ls -la build/libs

      - name: Build Docker Image
        run: |
          docker build -t xjl90/test_github_g:latest .  

      - name: Output Docker Username
        run: |
          echo "The Docker username is: ${{ secrets.DOCKER_USERNAME }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/test_github_g:latest
